### PR TITLE
fix: properly parse pure renames in git diffs

### LINKED ISSUE #1960: Patch application fails to do pure file renames
In https://github.com/conda-forge/tinygrad-feedstock/pull/4, I'm backporting https://github.com/tinygrad/tinygrad/commit/0f25b4b28954df4ea8ed489acbaa31265a1fafbe, which has two pure renames

Image

While the patches appear to get applied without issue
```
 │ │ Fetching source from url: https://github.com/tinygrad/tinygrad/archive/refs/tags/v0.10.3.tar.gz
 │ │ Found filename from Content-Disposition: tinygrad-0.10.3.tar.gz
 │ │ Downloaded file from https://github.com/tinygrad/tinygrad/archive/refs/tags/v0.10.3.tar.gz
 │ │ Validated SHA256 values of the downloaded file!
 │ │ Extracting tar file to cache: /home/conda/feedstock_root/build_artifacts/src_cache/tinygrad-0_10_3_ea91abf8.tar.gz
 │ │ Copying source from url: /home/conda/feedstock_root/build_artifacts/src_cache/tinygrad-0_10_3_ea91abf8 to /home/conda/feedstock_root/build_artifacts/bld/rattler-build_tinygrad_1761582177/work
 │ │ Applying patch: /home/conda/recipe_root/patches/0001-point-to-our-own-llvmdev.patch
 │ │ Applying patch: /home/conda/recipe_root/patches/0002-move-frontend-dir-to-nn-pr-12470.patch
 │ │
 │ ╰─────────────────── (took 3 seconds)
```
the files do not get renamed correctly.

### PR DESCRIPTION
**Pull request by wolfv**
A pure rename has no hunks, and this made the parser error out before. 

Now we treat it more carefully.

Should fix: https://github.com/prefix-dev/rattler-build/issues/1960

AI Disclaimer:

Most changes made by Claude :)

### CODE REVIEW

File: src/patch/parse.rs [hunk 1]
```diff
@@ -217,7 +233,7 @@ fn patch_header<'a, T: Text + ToOwned + ?Sized>(
     Option<(Cow<'a, [u8]>, Option<LineEnd>)>,
     Option<(Cow<'a, [u8]>, Option<LineEnd>)>,
 )> {
-    skip_header_preamble(parser)?;
+    let (git_original, git_modified) = skip_header_preamble(parser)?;
```
Comment (remimimimimi) [inline src/patch/parse.rs]: Maybe then it would make sense to rename `skip_header_preamble` to `header_preamble`?

File: src/patch/snapshots/diffy__patch__parse__tests__real_world_patches@pure-renames.patch.snap [hunk 2]
```diff
@@ -0,0 +1,991 @@
...
+                    "tinygrad/frontend/onnx.py",
+                ),
+            ),
+            modified: Some(
+                Filename(
+                    "tinygrad/nn/onnx.py",
+                ),
+            ),
+            hunks: [],
+        },
```
Comment (remimimimimi) [inline src/patch/snapshots/diffy__patch__parse__tests__real_world_patches@pure-renames.patch.snap:976]: Won't it cause problems if we will leave filenames without their usual a/b prefix?

**Review by remimimimimi — CHANGES_REQUESTED** [review]
Just couple of small comments, otherwise looks good to me!

File: src/patch/parse.rs (hunk 1 above)
Comment (wolfv) [reply src/patch/parse.rs]: Renamed! :)

File: src/patch/snapshots/diffy__patch__parse__tests__real_world_patches@pure-renames.patch.snap (hunk 2 above)
Comment (wolfv) [reply src/patch/snapshots/diffy__patch__parse__tests__real_world_patches@pure-renames.patch.snap:976]: It won't in our code in rattler-build (we are stripping them later anyways). 

I also made the code more robust because `git diff --no-prefix` can actually also produce files without that prefix. So now we are checking that both files start/end with `a/` or `b/`).

Now I am realizing that this logic might not work great for `/dev/null`...

Comment (remimimimimi) [reply src/patch/snapshots/diffy__patch__parse__tests__real_world_patches@pure-renames.patch.snap:976]: Don't we have special handling for `/dev/null` in rattler-build? @wolfv

Comment (wolfv) [reply src/patch/snapshots/diffy__patch__parse__tests__real_world_patches@pure-renames.patch.snap:976]: We just discussed this on Discord. The reasoning for stripping `a/` and `b/` here is that we have more information during patch parsing (e.g. we can observe if the patch starts with `diff --git ...`.

So stripping `a/` and `b/` is easier here.

Additionally, it is more necessary for these operations because they usually map from "/dev/null" -> "a/foobar". Now it's ambigous whether we need to strip or create a `a/` directory.
